name: Portfolio CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build: 
   runs-on: ubuntu-latest

   steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Install SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/contabo
          chmod 600 ~/.ssh/contabo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/contabo $SSH_USERNAME@$SERVER_IP "cd /var/www/me && git pull && npm install && npm run build"
        env:
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SERVER_IP: ${{ secrets.HOST }} 


   